In [1]:
# Transformers installation
#pip install transformers

from transformers import pipeline
classifier = pipeline('sentiment-analysis')

C:\Users\Ivan_Wizard\Desktop\KPI\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Downloading: 100%|██████████████████████████████████████████████████████████████████| 268M/268M [00:23<00:00, 11.3MB/s]
C:\Users\Ivan_Wizard\Desktop\KPI\venv\lib\site-packages\huggingface_hub\file_download.py:127: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Ivan_Wizard\.cache\huggingface\hub. Caching files will still work but in a degraded version 

In [2]:
txt_1 = 'Apple and Android`s rivalry is always a huge question to discuss'
classifier(txt_1)

[{'label': 'POSITIVE', 'score': 0.9864001274108887}]

In [3]:
txt_2 = 'Sea lions are pretty cool'
classifier(txt_2)

[{'label': 'POSITIVE', 'score': 0.999840497970581}]

In [4]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [5]:
inputs = tokenizer([txt_1, txt_2])

In [6]:
inputs

{'input_ids': [[101, 6207, 1998, 11924, 1036, 1055, 10685, 2003, 2467, 1037, 4121, 3160, 2000, 6848, 102], [101, 2712, 7212, 2024, 3492, 4658, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [7]:
inputs_with_padding = tokenizer([txt_1, txt_2], padding = True, truncation = True, max_length = 256, return_tensors="tf")

In [8]:
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[  101,  6207,  1998, 11924,  1036,  1055, 10685,  2003,  2467,
         1037,  4121,  3160,  2000,  6848,   102],
       [  101,  2712,  7212,  2024,  3492,  4658,   102,     0,     0,
            0,     0,     0,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])>}

In [9]:
outputs = model(inputs_with_padding)

In [10]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.1033661,  2.180639 ],
       [-4.187025 ,  4.556323 ]], dtype=float32)>, hidden_states=None, attentions=None)

In [11]:
import tensorflow as tf
predictions = tf.nn.softmax(outputs[0], axis=-1)

In [12]:
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.3599825e-02, 9.8640013e-01],
       [1.5949347e-04, 9.9984050e-01]], dtype=float32)>